title: DEVOPS STACK
author: Jefin Eldhose
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  DevOps is a set of practices that combines software development (Dev) and IT operations (Ops). 
  It aims to shorten the systems development life cycle and provide continuous delivery with high software quality.
  DevOps is complementary with Agile software development; several DevOps aspects came from the Agile methodology.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
# changeddd
